#include "ncc.h"
#include <malloc.h>
#include <stddef.h>
#include <stdio.h>

typedef enum global_type_t
{
	GLOB_CONST,
	GLOB_STR,
} global_type_t;

typedef struct global_t
{
	global_type_t type;
	node_val_t val;
} global_t;

typedef struct globals_t
{
	global_t *globals;
	size_t size;
	size_t cap;
} globals_t;

static globals_t GLOBALS = (globals_t){ .globals = NULL, .size = 0, .cap = 0 };

static int COMPILE_STATUS = 0;	/* 0 - normal, 1 - error */

static size_t LBL_CNT = 0;	/* label counter */
static size_t LOOP_LBL_CNT = 0;

static FILE *ASM_OUT = NULL;	/* pointer to asm file */

/*---------------------------------------------*/
static size_t NewGlobal(const global_t global);

static void GenGlobals(void);

static void GenDeclFunc(const node_t *ast);
static void GenAsm(const node_t *ast);
static void GenArifm(const node_t *ast);

static void GenExpr(const node_t *ast);
static void GenOr(const node_t *ast);
static void GenAnd(const node_t *ast);
static void GenComp(const node_t *ast, const op_t gle); /* Greater Less Equal*/

static void GenIf(const node_t *ast);
static void GenOpSeq(const node_t *ast);
static void GenOp(const node_t *ast);
static void GenAssign(const node_t *ast);
static void GenWhile(const node_t *ast);
static void GenCallFunc(const node_t *ast);
static void GenStr(const node_t *ast);

static void GenReturn(const node_t *ast);
static void GenBreak(const node_t *ast);
static void GenContinue(const node_t *ast);

static void GenDeref(const node_t *ast);
/*---------------------------------------------*/
#include "def_macro.h"
/*---------------------------------------------*/
int CompileTree(const node_t *ast, FILE *asm_out)
{
	if(ast == NULL || asm_out == NULL)
	{
		print_err_msg("nullptr passed as arg(s)");
		return 1;
	}
	if(!IS_(ROOT, ast->data))
	{
		print_err_msg("I wanna be a root");
		return 1;
	}

	ASM_OUT = asm_out;

	write_asm
		(
		 "; This file was generated by NCC v" NCC_VERSION "\n"
		 "; There is free software. There is NO warranty\n\n"
		 "global\t_start\n\n"
		);

	write_asm
		(
		 "_start:\n"
		 "\tcall\tmain\n"
		 "\tmov\trdi, rax\t; <'main' retval>\n"
		 "\tmov\trax, 0x3c\t; <exit>\n"
		 "\tsyscall\n\n"
		);

	child_t *decl = ast->child;
	while(decl)
	{
		if(decl->node == NULL)
		{
			print_err_msg("null node");
			return 1;
		}
		if(COMPILE_STATUS)
		{
			print_err_msg("compilation failed");
			return 1;
		}

		GenDeclFunc(decl->node);
		decl = decl->next;
	}

	write_asm("\n\nsection\t.rodata\n");
	GenGlobals();
	write_asm("\nsection\t.text\n");

	return COMPILE_STATUS;
}

static size_t NewGlobal(const global_t global)
{
	if(GLOBALS.size >= GLOBALS.cap)
	{
		GLOBALS.cap = (GLOBALS.cap+1)*2;
		GLOBALS.globals = (global_t *)reallocarray(GLOBALS.globals, GLOBALS.cap, sizeof(global_t));
		assert(GLOBALS.globals);
	}

	GLOBALS.globals[GLOBALS.size] = global;

	return GLOBALS.size++;
}

static void GenGlobals(void)
{
	for(size_t i = 0; i < GLOBALS.size; i++)
	{
		if(GLOBALS.globals[i].type == GLOB_STR)
		{
			const char *str = GLOBALS.globals[i].val.name;

			write_asm("_glob%lu:\n\tdq\t", i);

			while(*str)	write_asm("%ld, ", (long)*str++);

			write_asm("0\n");
		}
		else	err_exit_msg("global's type out of range");
	}
}
static void GenOp(const node_t *ast)
{
	assert(ast);
	assert(ASM_OUT);
	LEAVE_IF_ERR;

	switch(ast->data.type)
	{
		case TP_CALL_FUNC:	GenCallFunc(ast);	return;
		case TP_KWORD:
			switch(ast->data.val.kword)
			{
				case KW_ASM:		GenAsm(ast);		return;
				case KW_IF:		GenIf(ast);		return;
				case KW_WHILE:		GenWhile(ast);		return;
				case KW_RETURN:		GenReturn(ast);		return;
				case KW_PASS:					return;
				case KW_BREAK:		GenBreak(ast);		return;
				case KW_CONTINUE:	GenContinue(ast);	return;

				case KW_ELSE:
				case KW_FOR:		/* aren't implemented */
				case KW_FUNC:

				default:	err_exit_msg("invalid keyword");
			}
			return;

		case TP_OP:
			switch(ast->data.val.op)
			{
				case OP_ASSIGN:	GenAssign(ast);	return;

				case OP_ADD:
				case OP_SUB:
				case OP_MUL:
				case OP_DIV:
				case OP_MOD:
				case OP_GREATER:		/* implemented in GenArifm */
				case OP_LESS:
				case OP_EQ:
				case OP_NEQ:
				case OP_OR:
				case OP_AND:	GenArifm(ast);	return;

				default:	err_exit_msg("invalid operation");
			}
			return;

		case TP_EOF:
		case TP_ROOT:
		case TP_NUM:
		case TP_OP_SEQ:
		case TP_IDENT:
		case TP_PARAM:				/* cannot be operation */
		case TP_VAR:
		case TP_SYMB:
		case TP_DECL_FUNC:
		case TP_LITERAL:
		case TP_DEREF:
		case TP_TAKEADDR:
		default:	err_exit_msg("invalid type");
	}
}

static void GenStr(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	assert(ast->data.type == TP_LITERAL);

	write_asm
		(
		 "\tmov\trax, _glob%lu\t; <str>\n"
		 "\tshr\trax, 3\n"
		 "\tpush\trax\n",
		 NewGlobal((const global_t){ .type = GLOB_STR, .val = ast->data.val })
		);
}

static void GenOpSeq(const node_t *ast)
{
	assert(ast);
	assert(ASM_OUT);
	LEAVE_IF_ERR;		
	
	if (ast->data.type != TP_OP_SEQ)
		return GenOp(ast);

	child_t *op = ast->child;
	while(op)
	{
		assert(op->node);
		GenOp(op->node);
		op = op->next;
	}
}

static void GenArifm(const node_t *ast)
{
	assert(ast);
	assert(ASM_OUT);
	LEAVE_IF_ERR;

	switch(ast->data.type)
	{
		case TP_NUM:
			write_asm("\tpush\t%ld\t\n", ast->data.val.num);
			return;
		case TP_VAR:
			write_asm("\tpush\tqword [rbp%+ld*8]\t; <var>\n", ast->data.val.id);
			return;
		case TP_DEREF:
			GenDeref(ast);
			return;
		case TP_TAKEADDR:
			write_asm
				(
				 "\tlea\trax, [rbp%+ld*8]\t; <&>\n"
				 "\tshr\trax, 3\n"
				 "\tpush\trax\n",
				 ast->data.val.id
				);
			return;
		case TP_OP:
			if(!IS_BINNODE(ast))
				err_exit_msg("invalid node");

			GenExpr(LEFT(ast));
			GenExpr(RIGHT(ast));

			write_asm
				(
				 "\tpop\trcx\n"
				 "\tpop\trax\n"
				);

			switch(ast->data.val.op)
			{
				case OP_ADD:
					write_asm("\tadd\trax, rcx\n");
					break;
				case OP_SUB:
					write_asm("\tsub\trax, rcx\n");
					break;
				case OP_MUL:
					write_asm("\timul\trax, rcx\n");
					break;
				case OP_DIV:
				case OP_MOD:
					write_asm
						(
						 "\txor\trdx, rdx\n"
						 "\tidiv\trcx\n"
						);
					break;
				case OP_GREATER:
				case OP_LESS:
				case OP_ASSIGN:
				case OP_EQ:			/* implemented in GenComp, GenAnd, GenOr */
				case OP_NEQ:			/* implemented in GenComp, GenAnd, GenOr */
				case OP_OR:
				case OP_AND:

				default:	err_exit_msg("invalid operation");
			}

			if(ast->data.val.op == OP_MOD)	write_asm("\tpush\trdx\t; <%%>\n");
			else				write_asm("\tpush\trax\t; <arifm>\n");

			return;
		case TP_EOF:
		case TP_ROOT:
		case TP_OP_SEQ:
		case TP_IDENT:
		case TP_PARAM:
		case TP_KWORD:
		case TP_SYMB:
		case TP_DECL_FUNC:
		case TP_CALL_FUNC:
		case TP_LITERAL:
		default:
			err_exit_msg("invalid type");
	}
}

static void GenDeclFunc(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(ast->data.type != TP_DECL_FUNC)
		err_exit_msg("node is not a function declaration");
	if(!IS_BINNODE(ast))
		err_exit_msg("invalid declaration");

	write_asm
		(
		 "\n%s:\t; <decl>\n"
		 "\tenter\t%ld*8, 0\n",
		 ast->data.val.name,
		 ast->child->node->data.val.id + ast->child->next->node->data.val.id
		);

	GenOpSeq(RIGHT(ast));
	
	//write_asm("\tret\n\n"); /* dubiously */
}

static void GenAsm(const node_t *ast)
{
	assert(ast);
	assert(ASM_OUT);
	LEAVE_IF_ERR;
	if(!IS_(ASM, ast->data))
		err_exit_msg("is not 'asm'");
	if(!(ast->child && ast->child->node))
		err_exit_msg("invalid node");

	write_asm
		(
		 "; <asm inline>:\n"
		 "%s\n",
		 ast->child->node->data.val.name
		);
}

static void GenOr(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(!IS_(OR, ast->data))
		err_exit_msg("is not 'or'");
	if(!IS_BINNODE(ast))
		err_exit_msg("not binary 'or'");

	GenExpr(RIGHT(ast));
	GenExpr(LEFT(ast));

	write_asm
		(
		 "\t; <or>:\n"
		 "\tpop\trax\t; lval\n"
		 "\tpop\trdx\t; rval\n"
		 "\ttest\trax, rax\n"
		 "\tjne\t.L%lu\n"
		 "\ttest\trdx, rdx\n"
		 "\tjne\t.L%lu\n"
		 "\t; <result>:\n"
		 "\tpush\t0\n"
		 "\tjmp\t.L%lu\n"
		 ".L%lu:\n"
		 "\tpush\t1\n"
		 ".L%lu:\n",
		 LBL_CNT,
		 LBL_CNT,
		 LBL_CNT + 1,
		 LBL_CNT,
		 LBL_CNT + 1
		);

	LBL_CNT += 2;
}

static void GenAnd(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(!IS_(AND, ast->data))
		err_exit_msg("is not 'and'");
	if(!IS_BINNODE(ast))
		err_exit_msg("not binary 'and'");

	GenExpr(RIGHT(ast));
	GenExpr(LEFT(ast));

	write_asm
		(
		 "\t; <and>:\n"
		 "\tpop\trax\t; lval\n"
		 "\tpop\trdx\t; rval\n"
		 "\ttest\trax, rax\n"
		 "\tje\t.L%lu\n"
		 "\ttest\trdx, rdx\n"
		 "\tje\t.L%lu\n"
		 "\t; <result>:\n"
		 "\tpush\t1\n"
		 "\tjmp\t.L%lu\n"
		 ".L%lu:\n"
		 "\tpush\t0\n"
		 ".L%lu:\n",
		 LBL_CNT,
		 LBL_CNT,
		 LBL_CNT + 1,
		 LBL_CNT,
		 LBL_CNT + 1
		);

	LBL_CNT += 2;
}

static void GenComp(const node_t *ast, const op_t gle)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	
	if(!IS_BINNODE(ast))
		err_exit_msg("node is not binary");
	
	GenExpr(RIGHT(ast));
	GenExpr(LEFT(ast));

	const char *jmp_type = NULL;
	switch(gle)
	{
		case OP_GREATER:	jmp_type = "jg"; break;
		case OP_LESS:		jmp_type = "jl"; break;
		case OP_EQ:		jmp_type = "je"; break;
		case OP_NEQ:		jmp_type = "jne"; break;

		case OP_ADD:
		case OP_SUB:
		case OP_MUL:
		case OP_DIV:
		case OP_MOD:
		case OP_ASSIGN:
		case OP_OR:
		case OP_AND:

		default:		err_exit_msg("jmptype out of range");
	}

	write_asm
		(
		 "\t; <cmp>:\n"
		 "\tpop\trax\t; lval\n"
		 "\tpop\trdx\t; rval\n"
		 "\tcmp\trax, rdx\n"
		 "\t%s\t.L%lu\n"
		 "\tpush\t0\n"
		 "\tjmp\t.L%lu\n"
		 ".L%lu:\n"
		 "\tpush\t1\n"
		 ".L%lu:\n",
		 jmp_type, LBL_CNT,
		 LBL_CNT+1,
		 LBL_CNT,
		 LBL_CNT+1
		);

	LBL_CNT += 2;
}

static void GenExpr(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
		
	switch(ast->data.type)
	{
		case TP_NUM:
		case TP_VAR:
		case TP_TAKEADDR:
			GenArifm(ast);
			break;
		case TP_CALL_FUNC:
			GenCallFunc(ast);
			write_asm("\n\tpush\trax\t\t; <save retval>\n");
			break;
		case TP_DEREF:
			GenDeref(ast);
			break;
		case TP_OP:
			switch(ast->data.val.op)
			{
				case OP_ADD:
				case OP_SUB:
				case OP_MUL:
				case OP_DIV:
				case OP_MOD:
					GenArifm(ast);
					break;
				case OP_AND:
					GenAnd(ast);
					break;
				case OP_OR:
					GenOr(ast);
					break;
				case OP_GREATER:
				case OP_LESS:
				case OP_EQ:
				case OP_NEQ:
					GenComp(ast, ast->data.val.op);
					break;
				case OP_ASSIGN:
				default:
					err_exit_msg("invalid operation");
			}
			break;

		case TP_LITERAL:	GenStr(ast); break;

		case TP_EOF:
		case TP_ROOT:
		case TP_OP_SEQ:
		case TP_IDENT:
		case TP_PARAM:			/* cannot be expression */
		case TP_KWORD:
		case TP_SYMB:
		case TP_DECL_FUNC:
		default:
			err_exit_msg("type out of range");
	}
}

static void GenIf(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(!IS_(IF, ast->data))
		err_exit_msg("is not 'if'");

	child_t *child = ast->child;
	if(CHILD_EXISTS(child))
		GenExpr(child->node);
	else
		err_exit_msg("missing condition");
	child = child->next;

	size_t else_lbl = LBL_CNT++, endif_lbl = LBL_CNT++;
	
	/* condition */
	write_asm
		(
		 "\t; <if cnd>:\n"
		 "\tpop\trax\n"
		 "\ttest\trax, rax\n"
		 "\tje\t.L%lu\n"
		 "\t; <if body>\n",
		 else_lbl
		);

	/* 'if' body */
	if(CHILD_EXISTS(child))
		GenOpSeq(child->node);
	else
		err_exit_msg("missing 'if' body");
	child = child->next;

	/* 'else' body */
	write_asm
		(
		 "\tjmp\t.L%lu\n"
		 ".L%lu:\n"
		 "\t; <else body>\n",
		 endif_lbl, else_lbl
		);

	if(CHILD_EXISTS(child))
		GenOpSeq(child->node);

	/* endif */
	write_asm(".L%lu:\t; <endif>\n", endif_lbl);
}

static void GenWhile(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(!IS_(WHILE, ast->data))
		err_exit_msg("is not 'while'");
	if(!IS_BINNODE(ast))
		err_exit_msg("is not binary");

	size_t cond_lbl = LOOP_LBL_CNT++, end_lbl = LOOP_LBL_CNT++;

	write_asm
		(
		 "\t; <while cond>:\n"
		 ".Lloop%lu:\n",
		 cond_lbl
		);

	GenExpr(LEFT(ast));

	write_asm
		(
		 "\tpop\trax\n"
		 "\ttest\trax, rax\n"
		 "\tje\t.Lloop%lu\n"
		 "\t; <while body>:\n",
		 end_lbl
		);

	GenOpSeq(RIGHT(ast));

	write_asm
		(
		 "\tjmp\t.Lloop%lu\n"
		 ".Lloop%lu:\t; <while end>\n",
		 cond_lbl, end_lbl
		);
}

static void GenAssign(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(!IS_(ASSIGN, ast->data))
		err_exit_msg("is not 'assignment'");
	if(!IS_BINNODE(ast))
		err_exit_msg("is not binary");

	node_t *l_val = LEFT(ast);
	node_t *r_val = RIGHT(ast);

	/* r_val */
	if(r_val->data.type == TP_LITERAL)	GenStr(r_val);
	else					GenExpr(r_val);

	/* l_val */
	if(l_val->data.type == TP_VAR)
	{
		write_asm
			(
			 "\tpop\tqword [rbp%+ld*8]\t; <=>\n",
			 l_val->data.val.id
			);
	}
	else if(l_val->data.type == TP_DEREF)
	{
		if(!CHILD_EXISTS(l_val->child))
			err_exit_msg("wrong node");

		GenExpr(l_val->child->node);

		write_asm
			(
			 "\tpop\trax\n"
			 "\tshl\trax, 3\n"
			 "\tpop\tqword [rax]\t; <[]=>\n"
			);
	}
	else
		err_exit_msg("lvalue must be variable or dereference ptr");
}

static void GenCallFunc(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	assert(ASM_OUT);
	if(ast->data.type != TP_CALL_FUNC)
		err_exit_msg("is not a function call");
	if(ast->child == NULL || ast->child->node == NULL)
		err_exit_msg("call node without parameters node");

	write_asm("\t; <call>:\n");

	node_t *param_node = ast->child->node;

	if(param_node->child)
	{
		child_t *param = param_node->child->prev;

		for(ssize_t i = 0; i < param_node->data.val.id; i++)
		{
			assert(param);

			if(param_node->data.type == TP_LITERAL)	GenStr(param->node);
			else					GenExpr(param->node);

			param = param->prev;
		}
	}

	write_asm
		(
		 "\tcall\t%s\n"
		 "\tadd\trsp, %ld*8\t; rstr stack\n",
		 ast->data.val.name,
		 param_node->data.val.id
		);
}

static void GenReturn(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	if(!IS_(RETURN, ast->data))
		err_exit_msg("is not a 'return'");
	
	if(ast->child && ast->child->node)
	{
		GenExpr(ast->child->node);
		write_asm("\tpop\trax\t\t; <retval>\n");
	}
	else	write_asm("\tmov\trax, 0\t; dflt retval\n");

	write_asm
		(
		 "\tleave\n"
		 "\tret\n"
		);
}

static void GenBreak(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	if(!IS_(BREAK, ast->data))
		err_exit_msg("is not 'break'");

	write_asm("\tjmp\t.Lloop%lu\t; <break>\n", LOOP_LBL_CNT - 1);
}

static void GenContinue(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	if(!IS_(CONTINUE, ast->data))
		err_exit_msg("is not 'continue'");

	write_asm("\tjmp\t.Lloop%lu\t; <continue>\n", LOOP_LBL_CNT - 2);
}

static void GenDeref(const node_t *ast)
{
	LEAVE_IF_ERR;
	assert(ast);
	if(ast->data.type != TP_DEREF)
		err_exit_msg("is not '[]'");
	if(!CHILD_EXISTS(ast->child))
		err_exit_msg("wrong node");

	GenExpr(ast->child->node);

	write_asm
		(
		 "\tpop\trax\n"
		 "\tshl\trax, 3\n"
		 "\tpush\tqword [rax]\t; <[]>\n"
		);
}
/*---------------------------------------------*/
#include "undef_macro.h"
/*---------------------------------------------*/
